export const brandMappingActionTypes = {
    GETALL_BY_BRAND_REQUEST: 'BRAND_MAPPING_GETALL_BY_BRAND_REQUEST',
    GETALL_BY_BRAND_SUCCESS: 'BRAND_MAPPING_GETALL_BY_BRAND_SUCCESS',
    GETALL_BY_BRAND_FAILURE: 'BRAND_MAPPING_GETALL_BY_BRAND_FAILURE',

    CREATE_REQUEST: 'BRAND_MAPPING_CREATE_REQUEST',
    CREATE_SUCCESS: 'BRAND_MAPPING_CREATE_SUCCESS',
    CREATE_FAILURE: 'BRAND_MAPPING_CREATE_FAILURE',

    UPDATE_REQUEST: 'BRAND_MAPPING_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'BRAND_MAPPING_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'BRAND_MAPPING_UPDATE_FAILURE',

    DELETE_REQUEST: 'BRAND_MAPPING_DELETE_REQUEST',
    DELETE_SUCCESS: 'BRAND_MAPPING_DELETE_SUCCESS',
    DELETE_FAILURE: 'BRAND_MAPPING_DELETE_FAILURE',
};