export const brandActionTypes = {
    GETALL_REQUEST: 'BRANDS_GETALL_REQUEST',
    GETALL_SUCCESS: 'BRANDS_GETALL_SUCCESS',
    GETALL_FAILURE: 'BRANDS_GETALL_FAILURE',

    GETONE_REQUEST: 'BRANDS_GETONE_REQUEST',
    GETONE_SUCCESS: 'BRANDS_GETONE_SUCCESS',
    GETONE_FAILURE: 'BRANDS_GETONE_FAILURE',

    CREATE_REQUEST: 'BRANDS_CREATE_REQUEST',
    CREATE_SUCCESS: 'BRANDS_CREATE_SUCCESS',
    CREATE_FAILURE: 'BRANDS_CREATE_FAILURE',

    UPDATE_REQUEST: 'BRANDS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'BRANDS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'BRANDS_UPDATE_FAILURE',

    DELETE_REQUEST: 'BRANDS_DELETE_REQUEST',
    DELETE_SUCCESS: 'BRANDS_DELETE_SUCCESS',
    DELETE_FAILURE: 'BRANDS_DELETE_FAILURE',

    BLACKLIST_REQUEST: 'BRANDS_BLACKLIST_REQUEST',
    BLACKLIST_SUCCESS: 'BRANDS_BLACKLIST_SUCCESS',
    BLACKLIST_FAILURE: 'BRANDS_BLACKLIST_FAILURE',

    MOVE_TO_MAPPING_REQUEST: 'BRANDS_MOVE_TO_MAPPING_REQUEST',
    MOVE_TO_MAPPING_SUCCESS: 'BRANDS_MOVE_TO_MAPPING_SUCCESS',
    MOVE_TO_MAPPING_FAILURE: 'BRANDS_MOVE_TO_MAPPING_FAILURE',
};