export const brandImagesActionTypes = {
    GETALL_BY_BRAND_REQUEST: 'BRAND_IMAGES_GETALL_BY_BRAND_REQUEST',
    GETALL_BY_BRAND_SUCCESS: 'BRAND_IMAGES_GETALL_BY_BRAND_SUCCESS',
    GETALL_BY_BRAND_FAILURE: 'BRAND_IMAGES_GETALL_BY_BRAND_FAILURE',

    CREATE_REQUEST: 'BRAND_IMAGES_CREATE_REQUEST',
    CREATE_SUCCESS: 'BRAND_IMAGES_CREATE_SUCCESS',
    CREATE_FAILURE: 'BRAND_IMAGES_CREATE_FAILURE',

    UPDATE_REQUEST: 'BRAND_IMAGES_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'BRAND_IMAGES_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'BRAND_IMAGES_UPDATE_FAILURE',

    DELETE_REQUEST: 'BRAND_IMAGES_DELETE_REQUEST',
    DELETE_SUCCESS: 'BRAND_IMAGES_DELETE_SUCCESS',
    DELETE_FAILURE: 'BRAND_IMAGES_DELETE_FAILURE',

    SET_AS_MAIN_REQUEST: 'BRAND_IMAGES_SET_AS_MAIN_REQUEST',
    SET_AS_MAIN_SUCCESS: 'BRAND_IMAGES_SET_AS_MAIN_SUCCESS',
    SET_AS_MAIN_FAILURE: 'BRAND_IMAGES_SET_AS_MAIN_FAILURE',
};