export const brandUrlsActionTypes = {
    GETALL_BY_BRAND_REQUEST: 'BRAND_URLS_GETALL_BY_BRAND_REQUEST',
    GETALL_BY_BRAND_SUCCESS: 'BRAND_URLS_GETALL_BY_BRAND_SUCCESS',
    GETALL_BY_BRAND_FAILURE: 'BRAND_URLS_GETALL_BY_BRAND_FAILURE',

    CREATE_REQUEST: 'BRAND_URLS_CREATE_REQUEST',
    CREATE_SUCCESS: 'BRAND_URLS_CREATE_SUCCESS',
    CREATE_FAILURE: 'BRAND_URLS_CREATE_FAILURE',

    UPDATE_REQUEST: 'BRAND_URLS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'BRAND_URLS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'BRAND_URLS_UPDATE_FAILURE',

    DELETE_REQUEST: 'BRAND_URLS_DELETE_REQUEST',
    DELETE_SUCCESS: 'BRAND_URLS_DELETE_SUCCESS',
    DELETE_FAILURE: 'BRAND_URLS_DELETE_FAILURE',

    SET_AS_MAIN_REQUEST: 'BRAND_URLS_SET_AS_MAIN_REQUEST',
    SET_AS_MAIN_SUCCESS: 'BRAND_URLS_SET_AS_MAIN_SUCCESS',
    SET_AS_MAIN_FAILURE: 'BRAND_URLS_SET_AS_MAIN_FAILURE',
};